######################################################################
# Automatically generated by qmake (2.01a) jeu. d�c. 20 18:59:07 2007
######################################################################

TEMPLATE = app
TARGET = optiste
DEPENDPATH += . algo gui solver tests util
INCLUDEPATH += . util algo solver gui

# Input
HEADERS += Constraint.h \
           DetQuadProblem.h \
           LinearProblem.h \
           Objective.h \
           Problem.h \
           Solution.h \
           StochLinearProblem.h \
           Term.h \
           Variable.h \
           VariableBool.h \
           VariableFloat.h \
           VariableInt.h \
           algo/Algo.h \
           algo/SimulatedAnnealing.h \
           algo/VNS.h \
           gui/GUI.h \
           solver/LpsolveAdaptator.h \
           solver/Solver.h \
           util/FileParser.h \
           util/Logger.h \
           util/Random.h
FORMS += gui/GUI.ui
SOURCES += Constraint.cpp \
           DetQuadProblem.cpp \
           LinearProblem.cpp \
           Objective.cpp \
           Problem.cpp \
           Solution.cpp \
           StochLinearProblem.cpp \
           Term.cpp \
           Variable.cpp \
           VariableBool.cpp \
           VariableFloat.cpp \
           VariableInt.cpp \
           algo/Algo.cpp \
           algo/SimulatedAnnealing.cpp \
           algo/VNS.cpp \
           gui/GUI.cpp \
           gui/MainGUI.cpp \
           solver/LpsolveAdaptator.cpp \
           solver/Solver.cpp \
           util/FileParser.cpp \
           util/Logger.cpp \
           util/Random.cpp
